---
- name: Run WSL setup
  hosts: localhost
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update package caches if required
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

  tasks:
    - name: Install essential tools
      ansible.builtin.package:
        name:
          - curl
          - wget
          - unzip
          - vim
          - python3-pip
          - htop
          - build-essential

    - name: Install AWS CLI v2
      ansible.builtin.include_tasks:
        file: tasks/awscli.yml

    - name: Install Go
      ansible.builtin.include_tasks:
        file: tasks/go.yml

    - name: Install Terraform
      ansible.builtin.include_tasks:
        file: tasks/terraform.yml

  handlers:
    - name: Reload /etc/profile
      ansible.builtin.command: source /etc/profile
